/*
 * DotAAS Part 2 | HTTP/REST | Entire API Collection
 *
 * The entire API collection as part of Details of the Asset Administration Shell Part 2
 *
 * OpenAPI spec version: V1.0RC03
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace AAS.API.Models
{ 
        /// <summary>
        /// Gets or Sets ModelType
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ModelType
        {
            /// <summary>
            /// Enum AnnotatedRelationshipElementEnum for AnnotatedRelationshipElement
            /// </summary>
            [EnumMember(Value = "AnnotatedRelationshipElement")]
            AnnotatedRelationshipElementEnum = 0,
            /// <summary>
            /// Enum AssetAdministrationShellEnum for AssetAdministrationShell
            /// </summary>
            [EnumMember(Value = "AssetAdministrationShell")]
            AssetAdministrationShellEnum = 1,
            /// <summary>
            /// Enum BasicEventElementEnum for BasicEventElement
            /// </summary>
            [EnumMember(Value = "BasicEventElement")]
            BasicEventElementEnum = 2,
            /// <summary>
            /// Enum BlobEnum for Blob
            /// </summary>
            [EnumMember(Value = "Blob")]
            BlobEnum = 3,
            /// <summary>
            /// Enum CapabilityEnum for Capability
            /// </summary>
            [EnumMember(Value = "Capability")]
            CapabilityEnum = 4,
            /// <summary>
            /// Enum ConceptDescriptionEnum for ConceptDescription
            /// </summary>
            [EnumMember(Value = "ConceptDescription")]
            ConceptDescriptionEnum = 5,
            /// <summary>
            /// Enum DataSpecificationIEC61360Enum for DataSpecificationIEC61360
            /// </summary>
            [EnumMember(Value = "DataSpecificationIEC61360")]
            DataSpecificationIEC61360Enum = 6,
            /// <summary>
            /// Enum DataSpecificationPhysicalUnitEnum for DataSpecificationPhysicalUnit
            /// </summary>
            [EnumMember(Value = "DataSpecificationPhysicalUnit")]
            DataSpecificationPhysicalUnitEnum = 7,
            /// <summary>
            /// Enum EntityEnum for Entity
            /// </summary>
            [EnumMember(Value = "Entity")]
            EntityEnum = 8,
            /// <summary>
            /// Enum FileEnum for File
            /// </summary>
            [EnumMember(Value = "File")]
            FileEnum = 9,
            /// <summary>
            /// Enum MultiLanguagePropertyEnum for MultiLanguageProperty
            /// </summary>
            [EnumMember(Value = "MultiLanguageProperty")]
            MultiLanguagePropertyEnum = 10,
            /// <summary>
            /// Enum OperationEnum for Operation
            /// </summary>
            [EnumMember(Value = "Operation")]
            OperationEnum = 11,
            /// <summary>
            /// Enum PropertyEnum for Property
            /// </summary>
            [EnumMember(Value = "Property")]
            PropertyEnum = 12,
            /// <summary>
            /// Enum RangeEnum for Range
            /// </summary>
            [EnumMember(Value = "Range")]
            RangeEnum = 13,
            /// <summary>
            /// Enum ReferenceElementEnum for ReferenceElement
            /// </summary>
            [EnumMember(Value = "ReferenceElement")]
            ReferenceElementEnum = 14,
            /// <summary>
            /// Enum RelationshipElementEnum for RelationshipElement
            /// </summary>
            [EnumMember(Value = "RelationshipElement")]
            RelationshipElementEnum = 15,
            /// <summary>
            /// Enum SubmodelEnum for Submodel
            /// </summary>
            [EnumMember(Value = "Submodel")]
            SubmodelEnum = 16,
            /// <summary>
            /// Enum SubmodelElementCollectionEnum for SubmodelElementCollection
            /// </summary>
            [EnumMember(Value = "SubmodelElementCollection")]
            SubmodelElementCollectionEnum = 17,
            /// <summary>
            /// Enum SubmodelElementListEnum for SubmodelElementList
            /// </summary>
            [EnumMember(Value = "SubmodelElementList")]
            SubmodelElementListEnum = 18        }
}
